---
- name: install elasticsearch public signing key
  rpm_key: >
    state=present
    key=https://packages.elasticsearch.org/GPG-KEY-elasticsearch

- name: add yum elasticsearch repo
  template: >
    src=elasticsearch.repo
    dest=/etc/yum.repos.d

- name: install elasticsearch
  yum: >
    name=elasticsearch
  notify:
    - start elasticsearch

- name: flush handlers
  meta: flush_handlers

